export default [
  // season 1
  {
    id: 1,
    season: 1,
    episode: 1,
    title: "Both Ways",
    includesTim: true,
    categories: ["Season 1", "Includes Tim"],
  },
  {
    id: 2,
    season: 1,
    episode: 1,
    title: "Has This Ever Happened to You?",
    includesTim: true,
    categories: ["Season 1", "Includes Tim"],
  },
  {
    id: 3,
    season: 1,
    episode: 1,
    title: "Baby of the Year",
    includesTim: false,
    categories: ["Season 1"],
  },
  {
    id: 4,
    season: 1,
    episode: 1,
    title: "Instagram",
    includesTim: false,
    categories: ["Season 1"],
  },
  {
    id: 5,
    season: 1,
    episode: 1,
    title: "Gift Receipt",
    includesTim: true,
    categories: ["Season 1", "Includes Tim"],
  },
  {
    id: 6,
    season: 1,
    episode: 2,
    title: "Biker Guy",
    includesTim: true,
    categories: ["Season 1", "Includes Tim"],
  },
  {
    id: 7,
    season: 1,
    episode: 2,
    title: "River Mountain High, Part 1",
    includesTim: true,
    categories: ["Season 1", "Includes Tim"],
  },
  {
    id: 8,
    season: 1,
    episode: 2,
    title: "Wilson's Toupees",
    includesTim: false,
    categories: ["Season 1"],
  },
  {
    id: 9,
    season: 1,
    episode: 2,
    title: "Pink Bag",
    includesTim: true,
    categories: ["Season 1", "Includes Tim"],
  },
  {
    id: 10,
    season: 1,
    episode: 2,
    title: "River Mountain High, Part 2",
    includesTim: true,
    categories: ["Season 1", "Includes Tim"],
  },
  {
    id: 11,
    season: 1,
    episode: 2,
    title: "The Man",
    includesTim: true,
    categories: ["Season 1", "Includes Tim"],
  },
  {
    id: 12,
    season: 1,
    episode: 3,
    title: "Which Hand",
    includesTim: true,
    categories: ["Season 1", "Includes Tim"],
  },
  {
    id: 13,
    season: 1,
    episode: 3,
    title: "Focus Group",
    includesTim: true,
    categories: ["Season 1", "Includes Tim"],
  },
  {
    id: 14,
    season: 1,
    episode: 3,
    title: "Laser Spine Specialists",
    includesTim: true,
    categories: ["Season 1", "Includes Tim"],
  },
  {
    id: 15,
    season: 1,
    episode: 3,
    title: "New Joe",
    includesTim: false,
    categories: ["Season 1"],
  },
  {
    id: 16,
    season: 1,
    episode: 3,
    title: "Game Night",
    includesTim: true,
    categories: ["Season 1", "Includes Tim"],
  },
  {
    id: 17,
    season: 1,
    episode: 4,
    title: "Lifetime Achievement Award",
    includesTim: true,
    categories: ["Season 1", "Includes Tim"],
  },
  {
    id: 18,
    season: 1,
    episode: 4,
    title: "Christmas Carol",
    includesTim: false,
    categories: ["Season 1"],
  },
  {
    id: 19,
    season: 1,
    episode: 4,
    title: "Nachos",
    includesTim: true,
    categories: ["Season 1", "Includes Tim"],
  },
  {
    id: 20,
    season: 1,
    episode: 4,
    title: "Honk if You're Horny",
    includesTim: true,
    categories: ["Season 1", "Includes Tim"],
  },
  {
    id: 21,
    season: 1,
    episode: 5,
    title: "Brooks Brothers",
    includesTim: true,
    categories: ["Season 1", "Includes Tim"],
  },
  {
    id: 22,
    season: 1,
    episode: 5,
    title: "Choking",
    includesTim: true,
    categories: ["Season 1", "Includes Tim"],
  },
  {
    id: 23,
    season: 1,
    episode: 5,
    title: "New Printer",
    includesTim: true,
    categories: ["Season 1", "Includes Tim"],
  },
  {
    id: 24,
    season: 1,
    episode: 5,
    title: "The Day Robert Palin's Murdered Me",
    includesTim: true,
    categories: ["Season 1", "Includes Tim"],
  },
  {
    id: 25,
    season: 1,
    episode: 5,
    title: "The Babysitter",
    includesTim: true,
    categories: ["Season 1", "Includes Tim"],
  },
  {
    id: 26,
    season: 1,
    episode: 6,
    title: "Fenton's Stable and Horse Ranch",
    includesTim: false,
    categories: ["Season 1"],
  },
  {
    id: 27,
    season: 1,
    episode: 6,
    title: "Chunky",
    includesTim: true,
    categories: ["Season 1", "Includes Tim"],
  },
  {
    id: 28,
    season: 1,
    episode: 6,
    title: "Bozo Part 1",
    includesTim: true,
    categories: ["Season 1", "Includes Tim"],
  },
  {
    id: 29,
    season: 1,
    episode: 6,
    title: "Baby Shower",
    includesTim: true,
    categories: ["Season 1", "Includes Tim"],
  },
  {
    id: 30,
    season: 1,
    episode: 6,
    title: "Bozo Part 2",
    includesTim: true,
    categories: ["Season 1", "Includes Tim"],
  },
  {
    id: 31,
    season: 1,
    episode: 6,
    title: "Party House",
    includesTim: true,
    categories: ["Season 1", "Includes Tim"],
  },
  // season 2
  {
    id: 32,
    season: 2,
    episode: 1,
    title: "Lunch Meeting",
    includesTim: true,
    categories: ["Season 2", "Includes Tim"],
  },
  {
    id: 33,
    season: 2,
    episode: 1,
    title: "Coffin Flop",
    includesTim: true,
    categories: ["Season 2", "Includes Tim"],
  },
  {
    id: 34,
    season: 2,
    episode: 1,
    title: "Prank Show",
    includesTim: true,
    categories: ["Season 2", "Includes Tim"],
  },
  {
    id: 35,
    season: 2,
    episode: 1,
    title: "Little Buff Boys",
    includesTim: false,
    categories: ["Season 2"],
  },
  {
    id: 36,
    season: 2,
    episode: 1,
    title: "Ghost Tour",
    includesTim: true,
    categories: ["Season 2", "Includes Tim"],
  },
  {
    id: 37,
    season: 2,
    episode: 2,
    title: "The Capital Room",
    includesTim: false,
    categories: ["Season 2"],
  },
  {
    id: 38,
    season: 2,
    episode: 2,
    title: "Dan Flashes",
    includesTim: true,
    categories: ["Season 2", "Includes Tim"],
  },
  {
    id: 39,
    season: 2,
    episode: 2,
    title: "Diner Wink",
    includesTim: true,
    categories: ["Season 2", "Includes Tim"],
  },
  {
    id: 40,
    season: 2,
    episode: 2,
    title: "Shops at the Creek",
    includesTim: false,
    categories: ["Season 2"],
  },
  {
    id: 41,
    season: 2,
    episode: 2,
    title: "Baby Cries",
    includesTim: true,
    categories: ["Season 2", "Includes Tim"],
  },
  {
    id: 42,
    season: 2,
    episode: 3,
    title: "Graham's Lorelei Lounge",
    includesTim: true,
    categories: ["Season 2", "Includes Tim"],
  },
  {
    id: 43,
    season: 2,
    episode: 3,
    title: "Detective Crashmore Trailer",
    includesTim: false,
    categories: ["Season 2"],
  },
  {
    id: 44,
    season: 2,
    episode: 3,
    title: "HD Vac Commercial",
    includesTim: true,
    categories: ["Season 2", "Includes Tim"],
  },
  {
    id: 45,
    season: 2,
    episode: 3,
    title: "Detective Crashmore Press Junket",
    includesTim: false,
    categories: ["Season 2"],
  },
  {
    id: 46,
    season: 2,
    episode: 3,
    title: "Qualstarr Trial",
    includesTim: true,
    categories: ["Season 2", "Includes Tim"],
  },
  {
    id: 47,
    season: 2,
    episode: 4,
    title: "Wife Joke",
    includesTim: false,
    categories: ["Season 2"],
  },
  {
    id: 48,
    season: 2,
    episode: 4,
    title: "Friends Weekend",
    includesTim: true,
    categories: ["Season 2", "Includes Tim"],
  },
  {
    id: 49,
    season: 2,
    episode: 4,
    title: "Calico Cut Pants",
    includesTim: true,
    categories: ["Season 2", "Includes Tim"],
  },
  {
    id: 50,
    season: 2,
    episode: 5,
    title: "Parking Lot",
    includesTim: true,
    categories: ["Season 2", "Includes Tim"],
  },
  {
    id: 51,
    season: 2,
    episode: 5,
    title: "Del Frisco's Double Eagle",
    includesTim: false,
    categories: ["Season 2"],
  },
  {
    id: 52,
    season: 2,
    episode: 5,
    title: "Joanie's Birthday",
    includesTim: true,
    categories: ["Season 2", "Includes Tim"],
  },
  {
    id: 53,
    season: 2,
    episode: 5,
    title: "Dave Campor",
    includesTim: false,
    categories: ["Season 2"],
  },
  {
    id: 54,
    season: 2,
    episode: 5,
    title: "Mars Restaurant",
    includesTim: false,
    categories: ["Season 2"],
  },
  {
    id: 55,
    season: 2,
    episode: 6,
    title: "Dave Suit",
    includesTim: true,
    categories: ["Season 2", "Includes Tim"],
  },
  {
    id: 56,
    season: 2,
    episode: 6,
    title: "Driver's Ed",
    includesTim: true,
    categories: ["Season 2", "Includes Tim"],
  },
  {
    id: 57,
    season: 2,
    episode: 6,
    title: "Tammy Craps",
    includesTim: false,
    categories: ["Season 2"],
  },
  {
    id: 58,
    season: 2,
    episode: 6,
    title: "Big Wave",
    includesTim: true,
    categories: ["Season 2", "Includes Tim"],
  },
  {
    id: 59,
    season: 2,
    episode: 6,
    title: "Claire's",
    includesTim: false,
    categories: ["Season 2"],
  },
  // season 3
  {
    id: 60,
    season: 3,
    episode: 1,
    title: "Barley Tonight",
    includesTim: true,
    categories: ["Season 3", "Includes Tim"],
  },
  {
    id: 61,
    season: 3,
    episode: 1,
    title: "Mortal Enemies",
    includesTim: true,
    categories: ["Season 3", "Includes Tim"],
  },
  {
    id: 62,
    season: 3,
    episode: 1,
    title: "Summer Loving",
    includesTim: true,
    categories: ["Season 3", "Includes Tim"],
  },
  {
    id: 63,
    season: 3,
    episode: 1,
    title: "Street Sets",
    includesTim: false,
    categories: ["Season 3"],
  },
  {
    id: 64,
    season: 3,
    episode: 1,
    title: "The Driving Crooner",
    includesTim: true,
    categories: ["Season 3", "Includes Tim"],
  },
  {
    id: 65,
    season: 3,
    episode: 2,
    title: "Supermarket Swap VR Edition",
    includesTim: true,
    categories: ["Season 3", "Includes Tim"],
  },
  {
    id: 66,
    season: 3,
    episode: 2,
    title: "Darmine Doggy Door",
    includesTim: true,
    categories: ["Season 3", "Includes Tim"],
  },
  {
    id: 67,
    season: 3,
    episode: 2,
    title: "You Can't Park on the Sidewalk",
    includesTim: false,
    categories: ["Season 3"],
  },
  {
    id: 68,
    season: 3,
    episode: 2,
    title: "Nude Egg",
    includesTim: true,
    categories: ["Season 3", "Includes Tim"],
  },
  {
    id: 69,
    season: 3,
    episode: 2,
    title: "Sitcom Taping",
    includesTim: true,
    categories: ["Season 3", "Includes Tim"],
  },
  {
    id: 70,
    season: 3,
    episode: 3,
    title: "Richard Brecky as Jellybean",
    includesTim: true,
    categories: ["Season 3", "Includes Tim"],
  },
  {
    id: 71,
    season: 3,
    episode: 3,
    title: "Dog Hair",
    includesTim: true,
    categories: ["Season 3", "Includes Tim"],
  },
  {
    id: 72,
    season: 3,
    episode: 3,
    title: "Club Haunted House",
    includesTim: true,
    categories: ["Season 3", "Includes Tim"],
  },
  {
    id: 73,
    season: 3,
    episode: 3,
    title: "Pay it Forward",
    includesTim: true,
    categories: ["Season 3", "Includes Tim"],
  },
  {
    id: 74,
    season: 3,
    episode: 3,
    title: "Rat Mom",
    includesTim: false,
    categories: ["Season 3"],
  },
  {
    id: 75,
    season: 3,
    episode: 4,
    title: "Friend Group",
    includesTim: true,
    categories: ["Season 3", "Includes Tim"],
  },
  {
    id: 76,
    season: 3,
    episode: 4,
    title: "Pacific Proposal Park",
    includesTim: false,
    categories: ["Season 3"],
  },
  {
    id: 77,
    season: 3,
    episode: 4,
    title: "Gelutol",
    includesTim: true,
    categories: ["Season 3", "Includes Tim"],
  },
  {
    id: 78,
    season: 3,
    episode: 4,
    title: "Summer Loving Part 2",
    includesTim: true,
    categories: ["Season 3", "Includes Tim"],
  },
  {
    id: 79,
    season: 3,
    episode: 4,
    title: "Shirt Brothers",
    includesTim: true,
    categories: ["Season 3", "Includes Tim"],
  },
  {
    id: 80,
    season: 3,
    episode: 5,
    title: "Volcano",
    includesTim: true,
    categories: ["Season 3", "Includes Tim"],
  },
  {
    id: 81,
    season: 3,
    episode: 5,
    title: "Photo Booth",
    includesTim: false,
    categories: ["Season 3"],
  },
  {
    id: 82,
    season: 3,
    episode: 5,
    title: "House Party",
    includesTim: true,
    categories: ["Season 3", "Includes Tim"],
  },
  {
    id: 83,
    season: 3,
    episode: 6,
    title: "Banana Breath",
    includesTim: false,
    categories: ["Season 3"],
  },
  {
    id: 84,
    season: 3,
    episode: 6,
    title: "Photo Wall of Metal: Metal Motto Search",
    includesTim: false,
    categories: ["Season 3"],
  },
  {
    id: 85,
    season: 3,
    episode: 6,
    title: "Don Bondarley, King of Dirty Songs",
    includesTim: true,
    categories: ["Season 3", "Includes Tim"],
  },
  {
    id: 86,
    season: 3,
    episode: 6,
    title: "Tasty Time Vids",
    includesTim: true,
    categories: ["Season 3", "Includes Tim"],
  },
];
